export const GENERATE_OTP_REQUEST= 'GENERATE_OTP_REQUEST';
export const GENERATE_OTP_SUCCESS= 'GENERATE_OTP_SUCCESS';
export const GENERATE_OTP_FAILURE= 'GENERATE_OTP_FAILURE';
export const GENERATE_OTP_RESET= 'GENERATE_OTP_RESET';

export const VERIFY_OTP_REQUEST= 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS= 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE= 'VERIFY_OTP_FAILURE';
export const VERIFY_OTP_RESET= 'VERIFY_OTP_RESET';

export const GET_USER_REQUEST= 'GET_USER_REQUEST';
export const GET_USER_SUCCESS= 'GET_USER_SUCCESS';
export const GET_USER_FAILURE= 'GET_USER_FAILURE';

export const LOGIN_FAILURE= 'LOGIN_FAILURE';
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const LOGIN_REQUEST= 'LOGIN_REQUEST';
export const LOGIN_RESET= 'LOGIN_RESET';

export const SIGNUP_REQUEST= 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS= 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE= 'SIGNUP_FAILURE';

export const LOGOUT_REQUEST= 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS= 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE= 'LOGOUT_FAILURE';
